### PR TITLE
Clean up Arithmetic.Fin

### PR DESCRIPTION
**Pull request by andrewthad**
Commit message: Add left-plus and right-plus variants of bound-manipulation functions in Arithmetic.Fin. Document this convention. Rename raise to shift.

Agda uses the name `raise`. Idris uses `shift`. I think that `shift` is more appropriate of Haskell, since `raise` implies throwing an exception. I've removed the specializations of `shift` and `weaken` that increment by one since it is trivial for users to write `weakenL Nat.one fin`. In the cabal file, I've attempted to explain the convention of having left and right variants of functions. In practice, I've found that this makes this library considerably easier to use. Having to write `Plus.commutative` (often lifting it over another proof) makes for a miserable user experience and makes the resulting proofs unreadable.

@mckeankylej Wanted to get any of your thoughts.

### CODE REVIEW

**Comment by aljce** [comment]
These seem like good changes +1. One thing I was thinking about was if we should have variants of the functions with types like: 
```
zero :: Fin (n + 1)
last :: Nat n -> Fin (n + 1)
```
I decided against it in my implementation because its kinda hard to generated a proof that your number is of the form `n +1` with the current primitives exported.

**Comment by andrewthad** [comment]
Those two seem important for certain kinds of iteration, so I may end up having to add them at some point. Things I'm still planning on doing before merging this:

* Adding `weaken` for inequality and strict inequality.
* Adding variants of `ascending` and `descending` that act more like a fold so that users can avoid the GHC-wants-lists-to-be-CAFs problem.

**Comment by aljce** [comment]
Please keep the `ascending` versions. They are alot nicer to work with especially with things like `forM`. What is this CAF problem?

**Comment by aljce** [comment]
An [example](https://github.com/mckeankylej/contiguous-sized/blob/master/src/Data/Primitive/Contiguous/Sized.hs#L452) of a common use case I'd like to see supported. The interface exposed in `primitive-indexed` didn't support this usecase very well. You had to do something like:
```
flip ascendM foo bar $ \i -> ...
```

**Comment by andrewthad** [comment]
The issue I’m referring to is described at https://gitlab.haskell.org/ghc/ghc/issues/12620 and at https://gitlab.haskell.org/ghc/ghc/issues/8457.  The underlying problem is that data structures are simply not appropriate for control flow in high-performance code.  A lot of the time, people get lucky.  But, if the compiler ever figures out that the bounds between which you are iterating are static,  there is a very good chance that it will float the list out at a CAF,  leading to both a space leak and poorly performing generated code.

That aside, I’ll leave ascending and descending  since that is a common idiom,  but I’m adding the additional functions for more paranoid users like myself.

**Comment by andrewthad** [comment]
I've renamed `slice` to `ascendingSlice` since there may be a need for a `descendingSlice` somewhere down the road. I'm going to merge this and release to hackage shortly since this now has basically every operation that I need in order to build on top of it.

**Pull request merged**
